package xyz.linsage.model;

/**
 * Generated by linsage, do not modify this file.
 */
@SuppressWarnings("serial")
public  class Constant {
	 public static String name;
	 public static boolean devMode;

	 public static class db {
		 public static String url;
		 public static String user;
		 public static String password;
	}

	 public static class druid {
		 public static String initialSize;
		 public static String minIdle;
		 public static String maxActive;
		 public static String visitPath;
		 public static String logSlowSql;
		 public static String slowSqlMillis;
	}

	 public static class qiniu {
		 public static String accessKey;
		 public static String secretKey;
		 public static String separator;
		 public static String bucket;
		 public static String domain;

		 public static class ins {
			 public static String bucket;
			 public static String domain;
		}
	}

	 public static class httpProxy {
		 public static String ip;
		 public static int port;
	}
}
